# SPDX-FileCopyrightText: 2022 Daniel Valcour <fosssweeper@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
# Copyright (c) 2022 Daniel Valcour
#
# This file is part of FossSweeper.
#
# FossSweeper is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# FossSweeper is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with FossSweeper. If not, see <https://www.gnu.org/licenses/>.
#

#Compile automatic tests and run them, outputting errors

name: Release
on:
  workflow_dispatch:
    inputs:
      commitTag:
        description: "Tag"
        required: true
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              Name: Windows VS2019,
              os: windows-2019,
              cpack_generator: ZIP,
              package_extension: zip,
              cc: cl.exe,
              cxx: cl.exe,
              arch: "x64-windows",
            }
          - {
              Name: Linux GCC,
              os: ubuntu-20.04,
              cpack_generator: TGZ,
              package_extension: tar.gz,
              cc: gcc-10,
              cxx: g++-10,
              arch: "x64-linux",
            }
          - {
              Name: MacOS Clang,
              os: macos-10.15,
              cpack_generator: TGZ,
              package_extension: tar.gz,
              cc: clang,
              cxx: clang++,
              arch: "x64-osx",
            }
        build_type: [Release]
    env:
      buildDir: '${{ github.workspace }}\build'
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitTag }}
          submodules: 'recursive'
      - name: log CMake version
        shell: bash
        run: cmake --version
      - name: create build enviornment
        shell: bash
        working-directory: ${{ github.workspace }}
        run: cmake -E make_directory $GITHUB_WORKSPACE/build
      - name: xcode update
        if: ${{ runner.os == 'macOS'}}
        run: softwareupdate --install -a
      - name: apt update
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: sudo apt-get update
      - name: add linux system packages
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: sudo apt install libxinerama-dev libxcursor-dev xorg-dev libgtk-3-dev
      - name: generate CMake project
        shell: bash
        working-directory: ${{ github.workspace }}
        run: cmake -S . -B ./build/ -D FSWEEP_BUILD_TESTS=OFF
      - name: build CMake project
        shell: bash
        working-directory: ${{ github.workspace }}/build/
        run: cmake --build . --config ${{ matrix.build_type }}
      - name: run CPack to make a tar.gz
        shell: bash
        working-directory: ${{ github.workspace }}/build/
        run: cpack --config CPackConfig.cmake -G ${{ matrix.platform.cpack_generator }}
      - name: release the archive
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/build/*.${{ matrix.platform.package_extension }}
          draft: true
