# SPDX-FileCopyrightText: 2022 Daniel Valcour <fosssweeper@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

#
# Copyright (c) 2022 Daniel Valcour
#
# This file is part of FossSweeper.
#
# FossSweeper is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# FossSweeper is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with FossSweeper. If not, see <https://www.gnu.org/licenses/>.
#

#Compile automatic tests and run them, outputting errors

name: Release
on: 
  workflow_dispatch:
    inputs:
      commitTag:
        description: 'Tag'     
        required: true
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - {
              Name: Windows VS2019,
              os: windows-2019,
              executable: FossSweeper.exe,
              cc: cl.exe,
              cxx: cl.exe,
              arch: "x64-windows",
            }
        build_type: [Release]
    env:
      buildDir: '${{ github.workspace }}\build'
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commitTag }}
      - name: log CMake version
        shell: bash
        run: cmake --version
      - name: create build enviornment
        shell: bash
        working-directory: ${{ github.workspace }}
        run: cmake -E make_directory $GITHUB_WORKSPACE/build
      - name: generate CMake project
        shell: bash
        working-directory: ${{ github.workspace }}
        run: bash ./scripts/generate_no_tests.bash
      - name: build CMake project
        shell: bash
        working-directory: ${{github.workspace}}
        run: |
          cmake --build $GITHUB_WORKSPACE/build --config ${{ matrix.build_type }}
      - name: zip the release
        uses: vimtor/action-zip@v1
        with:
          files: build/modules/desktop_view/${{ matrix.platform.executable }} CHANGES
          dest: FossSweeper-${{ matrix.platform-os }}-${{ github.event.inputs.commitTag }}.zip
      - name: add the release
        uses: softprops/action-gh-release@v1
        with:
          files: FossSweeper-${{ matrix.platform-os }}-${{ github.event.inputs.commitTag }}.zip
          draft: true
